# Generated by Django 4.1.7 on 2023-02-21 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotel_shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelTableReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_of_guests", models.IntegerField(default=0)),
                ("num_of_tables", models.IntegerField()),
                ("reserve_table", models.BooleanField(default=False)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_shared.hotel",
                    ),
                ),
            ],
        ),
    ]
