# Generated by Django 4.1.7 on 2023-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=200)),
                (
                    "hotel_type",
                    models.CharField(
                        choices=[
                            ("ONE_STAR", "One Star Hotel"),
                            ("TWO_STAR", "Two Star Hotel"),
                            ("THREE_STAR", "Three Star Hotel"),
                            ("FOUR_STAR", "Four Star Hotel"),
                            ("FIVE_STAR", "Five Star Hotel"),
                            ("LUXURY", "Luxury Hotel"),
                            ("BUDGET", "Budget Hotel"),
                        ],
                        default="Three Star Hotel",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
